Initialize express js
PrivaNoteTeam/PrivaNote pull request #63
Opened 2021-09-22 23:42 UTC by EHSANHAZARI

2021-09-23 00:13 UTC, oliviergoulet5 commented
This code does not compile due to the following errors: 
```
Parameter '_' implicitly has an 'any' type.
Parameter '__' implicitly has an 'any' type.
```

This is because the `/` route's callback parameters do not have an explicit type as is required by the tsconfig. The reasons why this compiled properly on your machine may of been because the branch was being worked on prematurely (outdated main branch due to blockage). 

I would recommend you to delete the route entirely as it doesn't have any use in the main branch. Alternatively, you can add explicit types by [importing](https://stackoverflow.com/a/44610058) them from express.

Do this minor change and request again.

2021-09-23 21:28 UTC, oliviergoulet5 requested changes
Remove the `app.get` and resubmit.

2021-09-23 21:28 UTC, oliviergoulet5 commented on server/src/index.ts
> +    app.get('/', (_, __) => {
Should remove this `app.get` call because it generates errors with the tsconfig file due to not having explicit parameter types and it's not worth fixing since we don't need this route.

2021-09-23 23:37 UTC, oliviergoulet5 commented
Fantastic. Requested changes were implemented and the code runs. I'll approve this merge.

2021-09-23 23:37 UTC, oliviergoulet5 approved these changes

2021-09-24 00:13 UTC, thejasonxie approved these changes
Nice work setting up express. Express listens on port 8080 but had issues testing the root route.

2021-09-24 23:23 UTC, parsa111 approved these changes

2021-09-25 00:45 UTC, merged